FROM jrottenberg/ffmpeg:5.1-alpine

RUN mkdir /app
RUN mkdir /app/storage
RUN mkdir /app/storage/temp
RUN mkdir /app/storage/photos
RUN mkdir /app/storage/videos
RUN mkdir /app/storage/musics

COPY bin/fileService /app



WORKDIR /app
RUN chmod +x /app/fileService
ENTRYPOINT [ "sh", "./watch-and-run.sh", "./fileService"]