package migrations

type Views struct{}

func (*Views) up() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS views (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ip VARCHAR(16) NOT NULL,
            media_id BIGINT NOT NULL,
            user_id BIGINT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
            UNIQUE(user_id,media_id),
            FOREIGN KEY (media_id) REFERENCES medias (id) ON DELETE CASCADE,
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        );`,
	}
}

func (*Views) down() []string {
	return []string{
		`DROP TABLE IF EXISTS views;`,
	}
}

func (*Views) tableName() string {
	return "views"
}
