package migrations

type Comments struct{}

func (*Comments) up() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS comments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            text VARCHAR(512) NOT NULL,
            url VARCHAR(16) NOT NULL UNIQUE,
            user_id BIGINT NOT NULL,
            media_id BIGINT NOT NULL,
            comment_id BIGINT NULL, -- if be null shows its not a reply
            created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
            updated_at TIMESTAMP NULL,
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
            FOREIGN KEY (media_id) REFERENCES medias (id) ON DELETE CASCADE,
            FOREIGN KEY (comment_id) REFERENCES comments (id) ON DELETE CASCADE
        ); `, `
        CREATE OR REPLACE FUNCTION getCommentIdByUrl(commentUrl VARCHAR(16)) RETURNS BIGINT 
        AS $$ 
        DECLARE i BIGINT;
        BEGIN 
            SELECT id INTO i FROM comments WHERE url=commentUrl;
            IF i IS NULL THEN 
                RAISE EXCEPTION 'comment not found'; 
            END IF; 
            RETURN i;
        END; 
        $$ LANGUAGE PLPGSQL;
        `,
	}
}

func (*Comments) down() []string {
	return []string{
		`DROP FUNCTION IF EXISTS getCommentIdByUrl;`,
		`DROP TABLE IF EXISTS comments;`,
	}
}

func (*Comments) tableName() string {
	return "comments"
}
