package migrations

type Followings struct{}

func (*Followings) up() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS followings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            follower_id BIGINT NOT NULL,
            following_id BIGINT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
            FOREIGN KEY (follower_id) REFERENCES users (id) ON DELETE CASCADE,
            FOREIGN KEY (following_id) REFERENCES users (id) ON DELETE CASCADE,
            UNIQUE (follower_id,following_id)
        );`,
	}
}

func (*Followings) down() []string {
	return []string{
		`DROP TABLE IF EXISTS followings;`,
	}
}

func (*Followings) tableName() string {
	return "followings"
}
