package migrations

// up

type Users struct{}

func (*Users) up() []string {
	return []string{
		`
        CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email VARCHAR(128) NOT NULL UNIQUE,
            username VARCHAR(128) NOT NULL UNIQUE,
            channel_name VARCHAR(128) NOT NULL,
            about_me VARCHAR(512) NULL,
            hashed_password VARCHAR(128) NOT NULL,
            refresh_token VARCHAR(128) NOT NULL UNIQUE,
            refresh_token_expire TIMESTAMP NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
            updated_at TIMESTAMP NULL,
            email_verification VARCHAR(32) NULL UNIQUE,
            profile_photo VARCHAR(16) NULL UNIQUE,
            channel_photo VARCHAR(16) NULL UNIQUE
        );`,
		`
        CREATE OR REPLACE FUNCTION getUserIdByUsername(un VARCHAR(128)) RETURNS BIGINT 
        AS $$ 
        DECLARE i BIGINT;
        BEGIN 
            SELECT "id" INTO i FROM "users" WHERE "username"=un;
            IF i IS NULL THEN 
                RAISE EXCEPTION 'username not found'; 
            END IF; 
            RETURN i;
        END; 
        $$ LANGUAGE PLPGSQL;`,
	}
}

func (*Users) down() []string {
	return []string{
		`DROP FUNCTION IF EXISTS getUserIdByUsername;`,
		`DROP TABLE IF EXISTS users;`,
	}
}

func (*Users) tableName() string {
	return "Users"
}
