package migrations

type Likes struct{}

func (*Likes) up() []string {
	return []string{
		`
        CREATE TABLE IF NOT EXISTS likes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            is_like BOOLEAN NOT NULL DEFAULT TRUE,
            user_id BIGINT NOT NULL,
            media_id BIGINT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
            FOREIGN KEY (media_id) REFERENCES medias (id) ON DELETE CASCADE,
            UNIQUE (user_id,media_id)
        );
        `, `
        CREATE OR REPLACE FUNCTION getUserlikeOnMedia(userId BIGINT,mediaId BIGINT) RETURNS INT 
        AS $$ 
        DECLARE userLike INTEGER; 
        BEGIN 
            SELECT is_like INTO userLike FROM likes WHERE likes.media_id=mediaId AND likes.user_id=userId; 
            RETURN COALESCE(userLike,2); 
        END; 
        $$ LANGUAGE PLPGSQL;
        `,
	}
}

func (*Likes) down() []string {
	return []string{
		`DROP FUNCTION IF EXISTS getUserlikeOnMedia;`,
		`DROP TABLE IF EXISTS likes;`,
	}
}

func (*Likes) tableName() string {
	return "likes"
}
