package migrations

type Playlists struct{}

func (*Playlists) up() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS playlists (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(128) NOT NULL,
            url VARCHAR(16) NOT NULL UNIQUE,
            media_type SMALLINT NOT NULL, --0:video 1:music 2:photo 3:any
            thumbnail VARCHAR(16) NULL,
            text VARCHAR(1024) NOT NULL,
            user_id BIGINT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
            updated_at TIMESTAMP NULL,
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        );
        COMMENT ON COLUMN medias.media_type IS '0:video 1:music 2:photo 3:any';
        `, `
        CREATE OR REPLACE FUNCTION getPlaylistIdByUrl(playlistUrl VARCHAR(16)) RETURNS BIGINT 
        AS $$ 
        DECLARE i BIGINT;
        BEGIN 
            SELECT id INTO i FROM playlists WHERE url=playlistUrl;
            IF i IS NULL THEN 
                RAISE EXCEPTION 'playlist not found'; 
            END IF; 
            RETURN i;
        END; 
        $$ LANGUAGE PLPGSQL;`,
	}
}

func (*Playlists) down() []string {
	return []string{
		`DROP FUNCTION IF EXISTS getPlaylistIdByUrl;`,
		`DROP TABLE IF EXISTS playlists;`,
	}
}

func (*Playlists) tableName() string {
	return "playlist"
}
