package migrations

type Histories struct{}

func (*Histories) up() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS histories (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL,
            media_id BIGINT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
            FOREIGN KEY (media_id) REFERENCES medias (id) ON DELETE CASCADE
        );`,
	}
}

func (*Histories) down() []string {
	return []string{
		`DROP TABLE IF EXISTS histories;`,
	}
}

func (*Histories) tableName() string {
	return "histories"
}
